Part1
Dresmond/PFMCPP_Project3 pull request #1
Opened 2020-02-11 01:32 UTC by Dresmond

Removed spaces following "(" and proceeding ")" in parameter lists.

2020-02-20 13:38 UTC, Dresmond commented
Sending pull request to Matkat

2020-02-20 23:48 UTC, matkatmusic requested changes
2 things to implement.

2020-02-20 23:48 UTC, matkatmusic commented on main.cpp
> +    ElevatorCar car1;        // embedded structure
add a couple member functions.  Something like `moveToFloor(int floorNum);` or `moveToFloor(ElevatorFloor floor);`

- [ ] 3) add a couple member functions.

2020-02-20 23:48 UTC, matkatmusic commented on main.cpp
> +    ElevatorDoors doors;    // embedded structure
Add a member function that opens the doors. 

- [ ] 3) add a couple member functions.

2020-02-21 03:12 UTC, matkatmusic approved these changes

2020-02-21 03:12 UTC, merged